### model
model_name_or_path: xxx

### method
stage: sft
do_train: true
lora_target: all
weight_decay: 0.01

### dataset
dataset: texas_distill
template: default
overwrite_cache: true

### output
output_dir: xxx
logging_steps: 10
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 5.0e-5
num_train_epochs: 4.0
lr_scheduler_type: cosine
fp16: true
